version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgresql-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pms8   # Change this to your desired database name
      POSTGRES_USER: admin # Change this to your desired username
      POSTGRES_PASSWORD: admin # Change this to your desired password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
